apiVersion: apps/v1
kind: Deployment
metadata:
  name: service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service
  template:
    metadata:
      labels:
        app: service
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: service
        image: local/service:1.0
        imagePullPolicy: Never
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 8090
          name: service

---
apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 9080
    targetPort: 8090
  selector:
    app: service


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: auth
        image: local/auth:1.0
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 8090

---
apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  ports:
  - port: 9080
    targetPort: 8090
  selector:
    app: auth


# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: frontend
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: frontend
#   template:
#     metadata:
#       labels:
#         app: frontend
#     spec:
#       nodeSelector:
#         "beta.kubernetes.io/os": linux
#       containers:
#       - name: frontend
#         image: local/frontend:1.0
#         resources:
#           requests:
#             cpu: 100m
#             memory: 128Mi
#           limits:
#             cpu: 250m
#             memory: 256Mi
#         ports:
#         - containerPort: 8090

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: frontend
# spec:
#   type: LoadBalancer
#   ports:
#   - port: 9081
#     targetPort: 8090
#   selector:
#     app: frontend